version: '2'
services:

  django:
    build: .
    # Loading the app is defined here to allow for autoreload on changes it is
    # mounted on top of the old copy that docker added when creating the image
    volumes:
      - '.:/usr/src/app'
    environment:
      - DEBUG=True
      - DEBUG_SERVICES=True
      - DEBUG_LAYERS_NUMBER=50
      - REGISTRY_CHECK_PERIOD=15
    ports:
      - "8000:8000"

  celery:
    build: .
    volumes:
      - '.:/usr/src/app'
    environment:
      - DEBUG=True
      - REGISTRY_LIMIT_LAYERS=50
      - REGISTRY_CHECK_PERIOD=15

  elasticsearch:
    ports:
      - "9200:9200"

  maploom:
    image: terranodo/maploom:registry
    ports:
      - "3000:3000"

  nginx:
    image: terranodo/nginx:registry
    links:
      - django
      - elasticsearch
      - maploom
